mybbgroup/Thank-you-like-system

- inc/languages/english/admin/config_thankyoulike.lang.php
- inc/plugins/thankyoulike.php
Fix broken links in plugin description + security fix for possible SQL injection
> Fix broken links in plugin description + security fix

- inc/plugins/thankyoulike.php
Cosmetic change for postbit - list of users under the post
> Cosmetic change for postbit - list of users

- inc/languages/english/thankyoulike.lang.php
- inc/plugins/thankyoulike.php
- thankyoulike.php
Add MyAlerts support - thx to @Dark Neo for his amazing work!
> Add MyAlerts support

- inc/plugins/thankyoulike.php
Code looks fine - can we merge it into master branch? Now you are a contributor in master branch, so feel free to change code and make a PR. Thank you!
P.S. Is possible to contact you over email and ask you about something?
> Some typos in code description

- inc/plugins/thankyoulike.php
Dotted border-top for postbit_classic + bold text for thank you/like button
> Cosmetic changes

- inc/plugins/thankyoulike.php
> Fixes #43 - CSS part 3

- inc/languages/english/thankyoulike.lang.php
- inc/plugins/thankyoulike.php
- jscripts/thankyoulike.js
- thankyoulike.php
@WhiteNeo - I will merge your changes into master branch, it would be easier to maintain
> Fixes #38 + new popup notifications

- inc/languages/english/thankyoulike.lang.php
- inc/plugins/thankyoulike.php
Fixes #66 - () should not be shown in the popup window
@WhiteNeo - please could you verify this PR?
> Fixes #66 - () should not be shown in the popup window

- inc/languages/czech/thankyoulike.lang.php
> Czech lang - frontend

- inc/languages/portuguese/admin/config_thankyoulike.lang.php
- inc/languages/portuguese/admin/tools_thankyoulike_recount.lang.php
- inc/languages/portuguese/thankyoulike.lang.php
this add the Portuguese (Portugal) language to the PYL plugin.
> Portuguese (Portugal) language

- inc/plugins/thankyoulike.php
Updated author site link to latest mybb website eeplacing old mybbboard link.
> Updated author site link to latest mybb website

- inc/plugins/thankyoulike.php
Adds a "WHERE" SQL condition when rebuilding counts of
Likes/Thank Yous to take into account any forums excluded
via the "Excluded Forums" setting.
> Fixes #157

- README.md
- inc/languages/english/admin/config_thankyoulike.lang.php
- inc/plugins/thankyoulike.php
> Improvement for #159

- inc/plugins/thankyoulike.php
Fixes #147: Likes/Thanks are not merged upon User ID merge
> Fixes #147: Likes/Thanks are not merged upon User ID merge

- inc/plugins/thankyoulike.php
_Most Liked Post_ section in user profiles weren't sanitized.
> Fixes #200 - Sanitize Post/Thread Subjects

- inc/plugins/thankyoulike.php
> v3.1.0 release

- inc/plugins/thankyoulike.php
My try to fix this issue, need testing :)
#202
> Fixes #202

- jscripts/thankyoulike.js
Fixes #217
.... along with some other bugs and improvements / optimizations
> Fixes #217

- inc/plugins/thankyoulike.php
@lairdshaw - please review (just to make sure that I follow your idea in JS versioning)
> Preparing v3.3.6

- inc/languages/english/admin/config_thankyoulike.lang.php
- inc/plugins/thankyoulike.php
Doesn't implement the table of likes which @Eldenroot suggested in a comment in that issue - that should probably be opened as a separate issue.
> Implements #242, styling of received likes count.

- inc/plugins/thankyoulike.php
- thankyoulike.php
* (Re)creates the Master stylesheet on activation.
* Eliminates duplicated code via new functions.
* Eliminates hard-coded commas.
* Fixes a few coding style issues.
I have tested these changes a fair bit but it might be worth others testing too.
> Resolves issues #245, #246, and #247.

- inc/languages/english/thankyoulike.lang.php
- inc/plugins/thankyoulike.php
> Implement #248: Display date/time for top tyled post

- inc/plugins/thankyoulike.php
> Bump to v3.3.7

- inc/languages/english/admin/config_thankyoulike.lang.php
- inc/languages/english/thankyoulike.lang.php
- inc/plugins/thankyoulike.php
> Resolves #215 - TYL/THX counter extended for search.php

- inc/plugins/thankyoulike.php
> Resolve #254: Eliminate redundant code

- inc/languages/english/admin/config_thankyoulike.lang.php
- inc/plugins/thankyoulike.php
> Resolve #192: show full/simple navigation for member profile box

- inc/plugins/thankyoulike.php
> Fix #266: add missing global $prefix declaration

- inc/languages/english/admin/config_thankyoulike.lang.php
- inc/languages/english/thankyoulike.lang.php
- inc/plugins/thankyoulike.php
> Fix #244: statistics breakdown on member profile

- inc/plugins/thankyoulike.php
Resolve #265: Provide unformatted versions of all numerical values for use in templates
> Resolve #265

- inc/plugins/thankyoulike.php
@lairdshaw - are we ready to release? :)
I have been testing since yesterday, no issue so far.
> Preparing v 3.3.8

- inc/plugins/thankyoulike.php
> Fix #275: "new" indicator for alerts w/multi all-new tyls

- inc/plugins/thankyoulike.php
> Fix #276: remove underline for most tyled post link in member profile

- inc/plugins/thankyoulike.php
> Fix #274: Reuse of old alerts can make them hard to find

- inc/languages/english/thankyoulike.lang.php
- inc/plugins/thankyoulike.php
Fix #277 and more by reducing the number of language strings.
Also and incidentally fix some coding style issues.
> Fix #277: separate lang string for thanks and for likes

- inc/languages/english/thankyoulike.lang.php
- inc/plugins/thankyoulike.php
> Fix #278: create our own lang strings for time periods

- inc/plugins/thankyoulike.php
I think that we are ready to move forward and release a new minor version :) thank you again fro your contribution!
Btw - have you checked the MyBB Extend site? We are the fourth most starred project in total, and the third in the plugins group itself :)
https://community.mybb.com/mods.php
This is great and thats the purpose of open-source project :) it would not be possible without you and others contributors. I hope that this is not the end of our journey and we will move boundaries even further!
> Bump version number to 3.3.9

- inc/plugins/thankyoulike.php
> Prepare 3.4.0 :)

- upload/inc/plugins/thankyoulike.php
- upload/thankyoulike.php
> Resolve #327: Add the tyl_tnumtyls column back in

- php_errors.log
- upload/inc/languages/english/admin/config_thankyoulike.lang.php
- upload/inc/plugins/thankyoulike.php
> Resolve #302: add a setting to toggle core template changes

- upload/inc/plugins/thankyoulike.php
- upload/thankyoulike.php
- upload/tylsearch.php
> Fix #330: {1} not being replaced in jGrowl popup messages

- upload/inc/plugins/thankyoulike.php
> Fix #332: PHP warnings on post preview

- upload/inc/plugins/thankyoulike.php
> Prepare 3.4.5 version

- upload/inc/plugins/thankyoulike.php
See MyAlerts PR MyBBStuff/MyAlerts#297
> Update for new MyAlerts hook myalerts_register_client_alert_formatters

- upload/inc/plugins/thankyoulike.php
> Fix #341: PHP 8 warnings at ACP's Add New Promotion

- upload/inc/languages/english/thankyoulike.lang.php
- upload/inc/plugins/thankyoulike.php
Removes text styling from language file to allow for greater implementation into custom themes, allowing theme author/admin to designate styling options.
> Remove styling from Lang file

- upload/inc/plugins/thankyoulike.php
> Fix #346: PHP 8 warnings when previewing guest post

- upload/inc/plugins/thankyoulike.php
Recount tyls when members are deleted.
> Fix #348: Traces!

- upload/inc/plugins/thankyoulike.php
This refix:
1. Recognises that prior even to the first fix, the plugin already hooked in to a core member deletion routine. That hook - `admin_user_users_delete_commit` - though does not run in all scenarios in which users are deleted; notably, it does not run in scenarios in which multiple users are deleted at once. In this commit, then, we delete that now redundant preexisting hook-in which is superseded by the more generic one which we added in the first fix.
2. Replaces in that new, generic hook-in the call to our generic recount function with ad-hoc code after all, because, hey, why not be more efficient?
3. Handles the updating of unread alerts that are affected by having had tyls deleted due to their tyl'ing member having been deleted.
Refixes #348
> Refix #348: Traces!

- upload/inc/plugins/thankyoulike.php
This moves them closer to our gold standard, bringing them into closer alignment with those of other plugins our group maintains, including Link Tools and Image Auto-Resizer.
Bump version to 3.4.6 too. On merge of this commit/PR, we should be ready for a new release.
> Refactor+improve the (un)install/upgrade/(de)activate routines

- upload/inc/plugins/thankyoulike.php
Also standardise the regexes a little with respect to end-of-line and tab detection.
Resolves #354
> Fix #354: Template changes sometimes not undone on deactivation
